package com.Smileyes.nsfw.complain.entity;

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private String repId;
	private Complain complain;
	private String repName;
	private String repDept;
	private Date repTime;
	private String repContent;

	public Reply() {
	}

	public Reply(String repId, Complain complain, String repName, String repDept,
			Date repTime, String repContent) {
		this.repId = repId;
		this.complain = complain;
		this.repName = repName;
		this.repDept = repDept;
		this.repTime = repTime;
		this.repContent = repContent;
	}

	public String getRepId() {
		return this.repId;
	}

	public void setRepId(String repId) {
		this.repId = repId;
	}

	public Complain getComplain() {
		return this.complain;
	}

	public void setComplain(Complain complain) {
		this.complain = complain;
	}

	public String getRepName() {
		return this.repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

	public String getRepDept() {
		return this.repDept;
	}

	public void setRepDept(String repDept) {
		this.repDept = repDept;
	}

	public Date getRepTime() {
		return this.repTime;
	}

	public void setRepTime(Date repTime) {
		this.repTime = repTime;
	}

	public String getRepContent() {
		return this.repContent;
	}

	public void setRepContent(String repContent) {
		this.repContent = repContent;
	}

}
