package powerDesigner.entity;
// Generated 2017-9-1 20:02:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TCompany generated by hbm2java
 */
public class TCompany implements java.io.Serializable {

	private String coId;
	private String coName;
	private Set TDepts = new HashSet(0);

	public TCompany() {
	}

	public TCompany(String coId, String coName) {
		this.coId = coId;
		this.coName = coName;
	}

	public TCompany(String coId, String coName, Set TDepts) {
		this.coId = coId;
		this.coName = coName;
		this.TDepts = TDepts;
	}

	public String getCoId() {
		return this.coId;
	}

	public void setCoId(String coId) {
		this.coId = coId;
	}

	public String getCoName() {
		return this.coName;
	}

	public void setCoName(String coName) {
		this.coName = coName;
	}

	public Set getTDepts() {
		return this.TDepts;
	}

	public void setTDepts(Set TDepts) {
		this.TDepts = TDepts;
	}

}
