package powerDesigner.entity;
// Generated 2017-9-1 20:02:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TDept generated by hbm2java
 */
public class TDept implements java.io.Serializable {

	private String deptId;
	private TCompany TCompany;
	private String deptName;
	private Set TUsers = new HashSet(0);

	public TDept() {
	}

	public TDept(String deptId, TCompany TCompany, String deptName) {
		this.deptId = deptId;
		this.TCompany = TCompany;
		this.deptName = deptName;
	}

	public TDept(String deptId, TCompany TCompany, String deptName, Set TUsers) {
		this.deptId = deptId;
		this.TCompany = TCompany;
		this.deptName = deptName;
		this.TUsers = TUsers;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public TCompany getTCompany() {
		return this.TCompany;
	}

	public void setTCompany(TCompany TCompany) {
		this.TCompany = TCompany;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Set getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set TUsers) {
		this.TUsers = TUsers;
	}

}
