package powerDesigner.entity;
// Generated 2017-9-1 20:02:51 by Hibernate Tools 4.3.5.Final

/**
 * TLeader generated by hbm2java
 */
public class TLeader implements java.io.Serializable {

	private String userId;
	private TUser TUser;
	private String userName;
	private String deptId;
	private int place;

	public TLeader() {
	}

	public TLeader(TUser TUser, String userName, int place) {
		this.TUser = TUser;
		this.userName = userName;
		this.place = place;
	}

	public TLeader(TUser TUser, String userName, String deptId, int place) {
		this.TUser = TUser;
		this.userName = userName;
		this.deptId = deptId;
		this.place = place;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public int getPlace() {
		return this.place;
	}

	public void setPlace(int place) {
		this.place = place;
	}

}
