package powerDesigner.entity;
// Generated 2017-9-1 20:02:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TPrivilege generated by hbm2java
 */
public class TPrivilege implements java.io.Serializable {

	private String priId;
	private String priName;
	private Set TRoles = new HashSet(0);

	public TPrivilege() {
	}

	public TPrivilege(String priId, String priName) {
		this.priId = priId;
		this.priName = priName;
	}

	public TPrivilege(String priId, String priName, Set TRoles) {
		this.priId = priId;
		this.priName = priName;
		this.TRoles = TRoles;
	}

	public String getPriId() {
		return this.priId;
	}

	public void setPriId(String priId) {
		this.priId = priId;
	}

	public String getPriName() {
		return this.priName;
	}

	public void setPriName(String priName) {
		this.priName = priName;
	}

	public Set getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(Set TRoles) {
		this.TRoles = TRoles;
	}

}
