package powerDesigner.entity;
// Generated 2017-9-1 20:02:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private String userId;
	private TDept TDept;
	private String userName;
	private Set TRoles = new HashSet(0);
	private TLeader TLeader;

	public TUser() {
	}

	public TUser(String userId, TDept TDept, String userName) {
		this.userId = userId;
		this.TDept = TDept;
		this.userName = userName;
	}

	public TUser(String userId, TDept TDept, String userName, Set TRoles,
			TLeader TLeader) {
		this.userId = userId;
		this.TDept = TDept;
		this.userName = userName;
		this.TRoles = TRoles;
		this.TLeader = TLeader;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public TDept getTDept() {
		return this.TDept;
	}

	public void setTDept(TDept TDept) {
		this.TDept = TDept;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Set getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(Set TRoles) {
		this.TRoles = TRoles;
	}

	public TLeader getTLeader() {
		return this.TLeader;
	}

	public void setTLeader(TLeader TLeader) {
		this.TLeader = TLeader;
	}

}
